--Practica7
--Unidad1

CREATE DATABASE Restaurante
ON PRIMARY 
(
 NAME = 'Restaurante.mdf',
 FILENAME = 'C:\TBD2023\UNIDAD1\Restaurante.mdf'
 )
 LOG ON 
 (
 NAME = 'Restaurante.ldf',
 FILENAME = 'C:\TBD2023\UNIDAD1\Restaurante.ldf'
 );

 GO
 --Uso de la BD
 USE Restaurante; 

 CREATE TABLE INGREDIENTES
 (
  ING_ID INT IDENTITY(1,1) NOT NULL,
  ING_NOMBRE VARCHAR(50),
  ); 
  CREATE TABLE RECETAS
  (
   REC_ID INT IDENTITY(1,1) NOT NULL,
   RE_NOMBRE VARCHAR(100),
   CHEF_ID INT,
   REC_FECHAINCORPORACION DATE,
   TIPO_ID INT,
   REC_MODOPREPARACION VARCHAR(2000),
  );
  CREATE TABLE DET_RECETAS
  (
   REC_ID INT,
   ING_ID INT,
   ING_CANTIDAD INT,
   ING_MEDIDA VARCHAR(8)
   );
   CREATE TABLE TIPO_RECETAS
   (
    TIPO_ID INT IDENTITY(1,1) NOT NULL,
	TIPO_DESCRIPCION VARCHAR(50)
   ); 
   CREATE TABLE CHEFS
   (
    CHEF_ID INT IDENTITY(1,1) NOT NULL,
	CHEF_NOM VARCHAR(30),
   );

   --Creacion de cosntraints