--Practica13
--Unidad1

CREATE DATABASE Consultorio
ON PRIMARY
( 
 NAME = 'Consultorio.mdf',
 FILENAME = 'C:\TBD2023\UNIDAD1\Consultorio.mdf'
 )
 LOG ON 
 (
 NAME = 'Consultorio.ldf',
 FILENAME = 'C:\TBD2023\UNIDAD1\Consultorio.ldf'
 )
 GO
 
 USE Consultorio;

 CREATE TABLE TB_MEDICOS
 (
  MED_ID INT PRIMARY KEY NOT NULL,
  MED_NOMBRE VARCHAR(100),
  MED_CEDPROF VARCHAR(15),
  ESP_ID CHAR(3)
  );
  CREATE TABLE TB_ESPECIALIDADES
  (
   ESP_ID CHAR(3) PRIMARY KEY NOT NULL,
   ESP_NOMBRE VARCHAR(30),
   );
   CREATE TABLE TB_PACIENTES
   (
   PAC_ID VARCHAR(8) PRIMARY KEY NOT NULL,
   PAC_NOMBRE VARCHAR(50),
   PAC_TELEFONO VARCHAR(12)
   ); 
   CREATE TABLE TB_CITAS_MEDICAS
   (
   CITA_ID INT PRIMARY KEY NOT NULL,
   CITA_FECHA DATE,
   CITA_HORA TIME(7),
   PAC_ID VARCHAR(8),
   CITA_ASUNTO VARCHAR(200),
   MED_ID INT,
   );
   CREATE TABLE TB_EXPEDIENTE
   (
    EXP_ID INT PRIMARY KEY NOT NULL,
	PAC_ID VARCHAR(8),
	EXP_DIABETES CHAR(1),
	EXP_HIPERTENSION CHAR(1),
	EXP_CANCER CHAR(1),
	EXP_TIPOCANCER VARCHAR(100),
	EXP_ALERGIAS CHAR(1),
	EXP_TIPOLAERGIAS VARCHAR(100),
	EXP_TRANSFUSION CHAR(1),
	EXP_CIRUJIAS VARCHAR(100),
	EXP_TIPOCIRUJIAS VARCHAR(100),
	);
	CREATE TABLE TB_NOTAS_MEDICAS
	( 
	NOT_ID INT PRIMARY KEY NOT NULL,
	PAC_ID VARCHAR(8),
	NOT_MEDICA VARCHAR(600),
	NOT_FECHA DATE,
	NOT_MEDICAMENTO VARCHAR(200)
	);

	--Construccion de cosntraints

	ALTER TABLE TB_CITAS_MEDICAS
	ADD CONSTRAINT FK_CITAS_MEDICAS_MEDICOS 
	FOREIGN KEY (MED_ID)
	REFERENCES TB_MEDICOS(MED_ID);

	ALTER TABLE TB_CITAS_MEDICAS
	ADD CONSTRAINT FK_CITAS_MEDICAS_PACIENTE 
	FOREIGN KEY (PAC_ID)
	REFERENCES TB_PACIENTES(PAC_ID);
	
	ALTER TABLE TB_NOTAS_MEDICAS
	ADD CONSTRAINT FK_NOTAS_MEDICAS_PAC
	FOREIGN KEY (PAC_ID)
	REFERENCES TB_PACIENTES(PAC_ID);
	
	ALTER TABLE TB_EXPEDIENTE
	ADD CONSTRAINT FK_EXPEDIENTE_PAC
	FOREIGN KEY (PAC_ID)
	REFERENCES TB_PACIENTES(PAC_ID); 

