-- Practica 2
-- Unidad1
CREATE DATABASE Superheroes
ON PRIMARY 
(
NAME = 'Superheroes.mdf',
FILENAME = 'C:\TBD2023\UNIDAD1\Superheroes.mdf',
SIZE = 10MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 10%
)
LOG ON 
( 
NAME = 'Superheroes_log',
FILENAME = 'C:\TBD2023\UNIDAD1\Superheroes.ldf',
SIZE = 10MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 10%
) 
go 

use Superheroes

--Crear tablas

--Catalogo de lugares de defensa
CREATE TABLE LUGAR_DEFENSA(
  LUG_ID INT IDENTITY(1,1) PRIMARY KEY,
  LUG_NOMBRE VARCHAR(60) NULL
);
CREATE TABLE TRAJE(
   TRA_ID SMALLINT PRIMARY KEY,
   TRA_COLOR VARCHAR(30) NULL,
   TRA_MATERIAL VARCHAR(30) NULL DEFAULT 'SINTETICO',
   TRA_FOTO VARCHAR(200) NULL
);
CREATE TABLE PODER(
  POD_ID INT IDENTITY(10,10) NOT NULL,
  POD_NOMBRE VARCHAR(60) NULL,
  POD_TIPO VARCHAR(200) NULL DEFAULT 'ADQUIRIDO',
  CONSTRAINT PK_PODER PRIMARY KEY (POD_ID),
  CONSTRAINT CK_TIPO_PODER
  CHECK (POD_TIPO IN ('ADQUIRIDO','NACIMIENTO','HERRAMIENTA,TECNOLOGIA'))

);
 CREATE TABLE HEROE( 
  HER_ID INT IDENTITY(1,1) PRIMARY KEY,
  HER_NOMBRE VARCHAR(60) NULL,
  HER_ALIAS VARCHAR(30) NULL,
  HER_EDAD TINYINT NULL CHECK (HER_EDAD >=0),
  LUG_ID INT FOREIGN KEY REFERENCES LUGAR_DEFENSA(LUG_ID),
  HER_DESCRIPCION VARCHAR(200) NULL,
  TRA_ID SMALLINT FOREIGN KEY REFERENCES TRAJE(TRA_ID),
 );
 CREATE TABLE VILLANO(
  VILL_ID INT IDENTITY(1,1) NOT NULL,
  VILL_NOMBRE VARCHAR(70) NULL,
  VILL_ALIAS VARCHAR(30) NULL, 
  VILL_TRAJE SMALLINT NULL,
  CONSTRAINT PK_VILLANOS PRIMARY KEY(VILL_ID),
  CONSTRAINT FK_VILLANOS FOREIGN KEY(VILL_TRAJE) REFERENCES TRAJE(TRA_ID)
); 
CREATE TABLE UNIVERSO(
  UNI_ID TINYINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  UNI_NOMBRE VARCHAR(100),
  UNI_DESCRIPCION VARCHAR(MAX)
);
CREATE TABLE PODER_HEROE(
   HER_ID INT NOT NULL,
   POD_ID INT NOT NULL,
   CONSTRAINT PK_PODER_HEROE PRIMARY KEY(HER_ID,POD_ID),
   CONSTRAINT FK_PODER_HEROE_HEROE
   FOREIGN KEY(HER_ID) REFERENCES HEROE(HER_ID),
   CONSTRAINT FK_PODERES_HEROE_PODER
   FOREIGN KEY(POD_ID) REFERENCES PODER (POD_ID),
); 
CREATE TABLE PODER_VILLANO(
  VILL_ID INT NOT NULL,
  POD_ID INT NOT NULL,
  CONSTRAINT PK_PODER_VILLANO PRIMARY KEY(VILL_ID,POD_ID),
  CONSTRAINT FK_PODER_VILLANO_VILLANO
  FOREIGN KEY(VILL_ID) REFERENCES VILLANO(VILL_ID),
  CONSTRAINT FK_PODERES_VILLANO_PODER
  FOREIGN KEY(POD_ID) REFERENCES PODER (POD_ID)

); 
CREATE TABLE HEROEvsVILLANO(
 HER_ID INT NOT NULL,
 VILL_ID INT NOT NULL,
 CONSTRAINT PK_HEROEvsVILLANO PRIMARY KEY (HER_ID,VILL_ID),
 CONSTRAINT FK_HEROEvsVILLANO_HEROE
 FOREIGN KEY (HER_ID) REFERENCES HEROE(HER_ID),
 CONSTRAINT FK_HEROEvsVILLANO_VILANO
 FOREIGN KEY (VILL_ID) REFERENCES VILLANO(VILL_ID)
 ); 

 --Agregando Univeros a Heroe 

 ALTER TABLE HEROE 
 ADD UNI_ID TINYINT;

 --Creando la FK de Universo 
 ALTER TABLE HEROE
 ADD CONSTRAINT FK_HEROE_UNIVERSO
 FOREIGN KEY(UNI_ID)
 REFERENCES UNIVERSO(UNI_ID);

 --Agregar campo estrellas
 ALTER TABLE HEROE
 ADD HER_ESTRELLAS SMALLINT NULL;
 --Agregar CONSTRAINT de CHECK
 ALTER TABLE HEROE 
 ADD CONSTRAINT CK_ESTRELLAS_HEROE
 CHECK (HER_ESTRELLAS >= 1000 AND HER_ESTRELLAS <=10000);
 --Agregar CONSTRAINT DEFAULT 
 ALTER TABLE HEROE
 ADD CONSTRAINT DF_ESTRELLAS
 DEFAULT 100
 FOR HER_ESTRELLAS;

 