--Prcatica 5
--Unidad 1
CREATE DATABASE AgenciaAutomotriz --CREACION ESTANDAR DE BD
ON PRIMARY 
( 
 NAME = 'AgenciaAutomotriz.mdf',
 FILENAME = 'C:\TBD2023\UNIDAD1\AgenciaAutomotriz.mdf',
 SIZE = 12MB,
 MAXSIZE = UNLIMITED,
 FILEGROWTH = 10%
 )
 LOG ON 
 (
 NAME = 'AgenciaAutomotriz.ldf',
 FILENAME = 'C:\TBD2023\UNIDAD1\AgenciaAutomotriz.ldf',
 SIZE = 12MB,
 MAXSIZE = UNLIMITED,
 FILEGROWTH = 10%
 );

 GO

 --USO DE LA BD
 USE AgenciaAutomotriz; 

 --Creacion de las tablas a libertad
 CREATE TABLE CLIENTES
 (
  CLI_ID INT IDENTITY(1,1) NOT NULL,
  CLI_NOMBRE VARCHAR(60),
  CLI_DIRECCION VARCHAR(60),
  CLI_NUM_TEL VARCHAR(60),
  CLI_FECHA_NATO DATE,
  ); 
 CREATE TABLE VEHICULOS
 (
  CLI_ID_VEHICULO INT IDENTITY(1,1) NOT NULL,
  CLI_MARCA VARCHAR(20),
  CLI_MODELO VARCHAR(20),
  CLI_AÑO VARCHAR(4),
  CLI_PRECIO MONEY,
  ); 
  CREATE TABLE VENTAS
  (
  VEN_CLIENTE VARCHAR(60),
  VEN_ID_VEHICULO INT,
  VEN_PRECIO INT
  );
  CREATE TABLE EMPLEADOS
  (
  EMP_ID INT IDENTITY(1,1) NOT NULL,
  EMP_NOMBRE VARCHAR(30),
  EMP_CARO VARCHAR(60),
  EMP_SALARIO MONEY,
  );
  
  --CREACION DE CONSTRAINTS



